apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productcatalog
  template:
    metadata:
      labels:
        app: productcatalog
    spec:
      containers:
        - name: productcatalog
          image: dhananjaysingh2242/productcatalog:1.0
          ports:
            - containerPort: 8083

